### ISSUE TITLE
Broken package due to pydantic 2.0 upgrade

### ISSUE THREAD

**Issue by tibortakacs** [uranusjr/simpleindex#17]
The package is not compatible with pydantic 2.0.

**Comment by tibortakacs** [comment]
Here is a quick fix PR: https://github.com/uranusjr/simpleindex/pull/18

**Comment by uranusjr** [comment]
What is the error you see with pydantic 2? It would help fix the issue.

**Comment by tibortakacs** [comment]
```
usage: __main__.py [-h] config
__main__.py: error: argument config: invalid parse_arg value: '/__w/1/s/simpleindex.toml'
```
The path is valid, and the content of `simpleindex.toml` worked well with `pydantic<2`:
```toml
[routes."{package}"]
source="artifacts"
to="%PIP_INDEX_URL%:{package}"

[server]
host="127.0.0.1"
port=7192
log-level="error"
```
The first part is a internal simpleindex extension.
