### ISSUE TITLE
Route as '--find-links' replacement

### ISSUE THREAD

**Issue by sinoroc** [uranusjr/simpleindex#2]
I see people are [struggling with installing _pytorch_ on _Windows_, especially with _poetry_](https://github.com/python-poetry/poetry/issues/1391) since it does not know how to do something like _pip_'s `--find-links` option does. Would _simpleindex_ be able to help in such a scenario?

Typically the recommended installation command for Windows looks like:

```
pip install torch===1.7.0 torchvision===0.8.1 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
```

which seems to be impossible to do with _poetry_.

**Comment by uranusjr** [comment]
Assuming pytorch’s find-link page is valid HTML5 (I quickly checked and it seems to be the case), you should be able to just route all pytorch-related packages to it:

```toml
# Run `simpleindex path/to/this/file.toml` to start the server.
[routes.torch]
source = "http"
to = "https://download.pytorch.org/whl/torch_stable.html"

[routes."torch{suffix}"]
source = "http"
to = "https://download.pytorch.org/whl/torch_stable.html"

[routes."{project}"]
source = "http"
to = "https://pypi.org/simple/{project}/"

[host]
host = "127.0.0.1"
port = 8000
```

```toml
# Add this to `pyproject.toml`
[[tool.poetry.source]]
name = "local"
url = "http://127.0.0.1:8000/"
default = true
```

This should be able to make Poetry find the packages.

----

I said *should be* because it does not. Pytorch’s find-links page has links like this

```html
<a href="torch-0.1-cp27-cp27m-macosx_10_6_x86_64.whl">torch-0.1-cp27-cp27m-macosx_10_6_x86_64.whl</a>
```

Simpleindex uses 302 FOUND to redirect requests to the actual page, and Poetry would resolve `href` against `http://127.0.0.1:8000/pytorch/`, i.e. the original URL. pip instead resolves against the redirected URL.

PEP 503 does not really say what should happen when an endpoint returns redirection, but pip’s behaviour is likely more expected by users since that’s what every web browser in the world does, so Poetry should probably match it.
